### ISSUE TITLE
First attempt to load a document fails with Core version and Cache activated

### ISSUE THREAD

**Issue by obriankevin11** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#212]
Hi,
I cloned the repo, set the license key file and launched the [core demo project](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/tree/master/Demos/ASP.NET%20Core/).

STR
When I select a file for the very first time it displays for less than a second and disappears.
If I reselect the file then it shows up correctly and doesn't disappear.
If I relaunch the program, it shows up correctly on first and subsequent openings.

Microsoft Visual Studio Professional 2022 (64-bit) 
Version 17.0.4

Tested with browsers, same issue on both:
Brave is up to date [Version 1.36.122 Chromium: 99.0.4844.88 (Official Build) (64-bit)](https://brave.com/latest/)
Google Chrome Version 98.0.4758.102 (Official Build) (32-bit)

I commented out the .AddLocalCache("./Cache"); and the issue doesn't happen.

**Comment by harumburum** [comment]
@obriankevin11 

I'm sorry for the delayed response. Thank you for sharing the details about the issue. Unfortunately, I've failed to reproduce it on my end. We'll continue investigating this issue and share the results with you here.

**Comment by vladimir-litvinchik** [comment]
@obriankevin11

I'm sorry for the delayed response. Thank you for sharing the details about the issue. Unfortunately, I've failed to reproduce it on my end. We'll continue investigating this issue and share the results with you here.

**Comment by mikhail-evgrafov** [comment]
@obriankevin11

How did you launch your project?
Might you try to check with dotnet run from command-line?

**Comment by mikhail-evgrafov** [comment]
Might you do following:
1) Clear cache
2) Reload the page
3) Open the console by F12
4) Click on settings (see pointers)
5) Click on "Preserve log"
![image](https://user-images.githubusercontent.com/63582936/160567297-aa7c6a83-0dd7-4ca5-a678-b20e5774a74f.png)
6) Upload the document
7) Attach browse console here

I want to check that issue was caused by asp.net hot reload with the browser link.

**Comment by mikhail-evgrafov** [comment]
Might you scroll your console output to the top and check for "File change detected"?
Don't forget to clear cache directory and reload the page before.
![image](https://user-images.githubusercontent.com/63582936/160577788-56bda322-86b3-4223-8121-9a8496cc3f2a.png)

**Comment by obriankevin11** [comment]
[Link to HAR file](https://drive.google.com/file/d/1OwXSlD20znRkwSvRxOhaCNGNdh9LkpLX/view?usp=sharing)

**Comment by mikhail-evgrafov** [comment]
@obriankevin11 might you paste console log here?

**Comment by mikhail-evgrafov** [comment]
@obriankevin11 not requests log, but text console messages

**Comment by obriankevin11** [comment]
logs [here](https://drive.google.com/file/d/1kMf5D_o8p6_W4bHnz5CcRuO8yXH5vYfl/view?usp=sharing)

**Comment by mikhail-evgrafov** [comment]
Look at text log:
aspnetcore-browser-refresh.js:68 File change detected to css file /Cache/11sample_docx/p1.html. Reloading page...
aspnetcore-browser-refresh.js:68 File change detected to css file /Cache/11sample_docx/p2.html. Reloading page...
aspnetcore-browser-refresh.js:68 File change detected to css file /Cache/11sample_docx/p2.html. Reloading page...
aspnetcore-browser-refresh.js:68 File change detected to css file /Cache/11sample_docx/p1.html. Reloading page...

So your issue is related to AspNet core browser link auto-refresh. It is because of you running your project from Visual Studio, this feature designed specifically for Development to auto-refresh page when you update your Javascript/HTML markup, TS modules. It will not on product, only when you running your project from Visual Studio for development.

**Comment by mikhail-evgrafov** [comment]
@obriankevin11 

If you don't need this feature (useful for development purposes only, when you work under UI scripts/markup), you can disable this feature:
1. Open Demos\ASP.NET Core\src\Properties\launchSettings.json
2. Add "hotReloadEnabled": false, under "applicationUrl"

So your launchSettings.json will look as:
```
{
  "profiles": {
    "GroupDocs.Viewer.AspNetCore": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "launchUrl": "viewer",
      "applicationUrl": "https://localhost:9091;http://localhost:8080",
      "hotReloadEnabled": false,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}

```

**Comment by obriankevin11** [comment]
ok great, problem solved.
thank you

**Comment by mikhail-evgrafov** [comment]
@obriankevin11 

You are welcome!
